"""
agents/report_writer/report_writer_agent.py
---------------------------------------------
Report Writer Agent
---------------------
Role: Transforms the structured EnsembleOutput into a beautiful, human-readable
markdown report suitable for display in the frontend.

The report includes:
  • A clear overall prediction headline
  • Ranked indicator breakdown with citations
  • Mainstream vs. under-covered classification for each signal
  • A prominent uncertainty/disclaimer section
  • Price context (recent history from the Price Data Agent)

This is a pure text-generation agent — it calls no external tools.
"""

import os
import sys
import json
import logging
from typing import Optional

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(os.path.dirname(_HERE))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from dotenv import load_dotenv
load_dotenv(os.path.join(_ROOT, ".env"))

from google.adk import Agent
from google.adk.runners import InMemoryRunner
from google.genai import types

from agents.schemas import EnsembleOutput

logger = logging.getLogger(__name__)


report_writer_agent = Agent(
    name="report_writer_agent",
    model="gemini-2.5-flash",
    description="Report Writer Agent – converts ensemble output into a readable markdown report",
    instruction="""
You are a senior financial journalist and analyst.  Your job is to write a clear,
insightful, and beautifully formatted markdown report based on the structured
analysis data you receive.

REPORT STRUCTURE (follow exactly):

# [TICKER] Stock Analysis Report — [DATE]

## Overall Prediction
**Direction:** [BULLISH/BEARISH/NEUTRAL]  
**Confidence:** [X%]  
**Estimated Impact:** [magnitude_range]

One-sentence summary of the call.

## Ranked Signal Breakdown

For each indicator (in ranked order), write a section:

### [RANK]. [Indicator Name] — [SIGNAL] (Confidence: X%)
**Coverage Type:** [MAINSTREAM / UNDER-COVERED]
**Data Lag:** [N days]

[2-3 sentences of reasoning]

**Key Evidence:**
- [Evidence 1]
- [Evidence 2]

**Sources:** [source URLs]

---

## Why This Matters

[3-4 sentence synthesis explaining the overall narrative and what drives the call]

## ⚠ Uncertainty & Disclaimer

[uncertainty_statement from ensemble + note that this is public-data analysis only,
not investment advice, and past patterns do not guarantee future returns]

---
*Report generated by the MedTech AI Stock Analyst multi-agent system*
*Data as of: [DATE] | Powered by Google ADK + MCP*

IMPORTANT RULES:
- Use the exact data provided — do not invent statistics.
- Be specific: cite exact numbers, percentages, and source names.
- Keep a professional but accessible tone.
- The uncertainty section must be prominent and honest.
""",
    tools=[],
)


async def run(
    ticker: str,
    as_of_date: Optional[str],
    ensemble: EnsembleOutput,
    indicators: list,
    price_context: dict,
) -> str:
    """
    Generate a human-readable markdown report.

    Parameters
    ----------
    ticker : str
    as_of_date : str | None
    ensemble : EnsembleOutput
    indicators : list[IndicatorOutput]
    price_context : dict  Price history from Price Data Agent

    Returns
    -------
    str  Markdown-formatted report.
    """
    try:
        report_date = as_of_date or "Today"
        ensemble_dict = ensemble.model_dump() if hasattr(ensemble, "model_dump") else ensemble
        indicators_list = [
            ind.model_dump() if hasattr(ind, "model_dump") else ind
            for ind in indicators
        ]

        msg = (
            f"Write a detailed stock analysis report for {ticker} as of {report_date}.\n\n"
            f"ENSEMBLE RESULT:\n{json.dumps(ensemble_dict, indent=2)}\n\n"
            f"INDICATOR DETAILS:\n{json.dumps(indicators_list, indent=2)}\n\n"
            f"PRICE CONTEXT:\n{json.dumps(price_context, indent=2)}\n\n"
            "Follow your instructions to write the full markdown report."
        )

        runner = InMemoryRunner(agent=report_writer_agent, app_name="medtech_analyst")
        session = await runner.session_service.create_session(
            app_name="medtech_analyst", user_id="analyst"
        )
        events = []
        async for event in runner.run_async(
            user_id="analyst",
            session_id=session.id,
            new_message=types.UserContent(parts=[types.Part(text=msg)]),
        ):
            events.append(event)

        # Collect text from the last model turn
        report_parts = []
        for event in events:
            if event.content and event.content.parts:
                for part in event.content.parts:
                    if part.text:
                        report_parts.append(part.text)

        if report_parts:
            return "".join(report_parts)

        # Minimal fallback
        direction = ensemble_dict.get("direction", "neutral").upper()
        confidence = ensemble_dict.get("confidence", 0.0)
        return (
            f"# {ticker} Stock Analysis — {report_date}\n\n"
            f"**Overall Signal:** {direction} (confidence: {confidence:.0%})\n\n"
            f"**Magnitude:** {ensemble_dict.get('magnitude_range', 'N/A')}\n\n"
            f"{ensemble_dict.get('synthesized_reasoning', '')}\n\n"
            f"---\n*{ensemble_dict.get('uncertainty_statement', '')}*"
        )

    except Exception as exc:
        logger.error("report_writer_agent failed for %s: %s", ticker, exc)
        return f"# {ticker} Analysis Report\n\nReport generation failed: {exc}"
